Simulate error and rollback #22

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -33,7 +33,11 @@ jobs:
           env:
             FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
         - name: Check App Health
-          run: | 
-            response=$(curl -o /dev/null -s -w "%{http_code}\n" https://yannis-sefsaf-full-stack-open-pokedex.fly.dev/health) if [ "$response" != "200" ]; then echo "Health check failed with status code: $response" exit 1 fi
+          run: |
+            response=$(curl -o /dev/null -s -w "%{http_code}\n" https://yannis-sefsaf-full-stack-open-pokedex.fly.dev/health)
+            if [ "$response" != "200" ]; then
+            echo "Health check failed with status code: $response"
+            exit 1
+            fi
           env:
             FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
